<<<<<<< HEAD:auth/account/migrations/0001_initial.py
# Generated by Django 5.2.7 on 2025-11-03 17:19
=======
# Generated by Django 5.2.7 on 2026-02-27 18:06
>>>>>>> upstream/main:main/account/migrations/0001_initial.py

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp', models.CharField(blank=True, max_length=255, null=True)),
                ('last_otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('otp_exp', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.IntegerField(default=0)),
                ('otp_locked_until', models.DateTimeField(blank=True, null=True)),
                ('otp_type', models.CharField(blank=True, choices=[('registration', 'Registration'), ('password_reset', 'Password Reset')], max_length=20, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
    ]
