name: Django CI/CD

on:
  push:
    branches:
      - main
      - development
      - authentication
      - pushkar
      - Arnav

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r auth/requirements.txt

      - name: Run tests
        run: |
          cd auth
          python manage.py test

      - name: Deploy to EC2
        if: |
          github.ref == 'refs/heads/main' || 
          github.ref == 'refs/heads/development' || 
          github.ref == 'refs/heads/authentication'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/tripsync-backend/auth
            git pull origin $GITHUB_REF_NAME
            source ../env/bin/activate
            pip install -r ../requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
